[WIP] Prototype of DataJointWorker and WorkerLog
ttngu207/sciops-demo-workflow-1 pull request #9
Opened 2021-10-27 21:30 UTC by ttngu207

2021-10-29 21:53 UTC, dimitri-yatsenko requested changes

2021-10-29 21:53 UTC, dimitri-yatsenko commented on workflow/djworker.py
> +    _table_name = '~WorkerLog'
we use lower snake case for all table names
```suggestion
    _table_name = '~worker_log'
```

2021-10-29 21:53 UTC, dimitri-yatsenko commented on workflow/djworker.py
> +
else raise error?

2021-10-29 21:53 UTC, dimitri-yatsenko commented on workflow/djworker.py
> +    def print_recent_jobs(cls, backtrack_minutes=60):
This function does not print.  So change the name.
```suggestion
    def recent_jobs(cls, backtrack_minutes=60):
```

2021-10-29 21:53 UTC, dimitri-yatsenko commented on workflow/djworker.py
> +                (cls & old_jobs).delete()
consider using `delete_quick`
```suggestion
                (cls & old_jobs).delete_quick()
```

2021-10-29 21:53 UTC, dimitri-yatsenko commented on workflow/djworker.py
> +               or (self._run_duration < 0)):
```suggestion
        while (time.time() - start_time < self._run_duration
               or self._run_duration is None
               or self._run_duration < 0):
```

2021-10-29 21:53 UTC, dimitri-yatsenko commented on workflow/djworker.py
> +                    process.populate(**{**_populate_settings, **kwargs})
```suggestion
                    process.populate(**_populate_settings, **kwargs)
```

2021-10-29 21:53 UTC, dimitri-yatsenko commented on workflow/process.py
> +def auto_generate_clustering_tasks():
I suggest using simplifying to `generate_clustering_tasks`

2021-10-29 21:53 UTC, dimitri-yatsenko commented on workflow/process.py
> +def auto_generate_probe_insertions():
Consider simplifying to `generate_probe_insertions`

2021-12-01 06:59 UTC, guzman-raphael commented
@ttngu207 Now that we have [datajoint-utilities](https://github.com/vathes/datajoint-utilities), would you mind moving this there?

2021-12-10 17:06 UTC, ttngu207 commented
Closing this PR, moving this `DataJointWorker` mechanism to: https://github.com/vathes/datajoint-utilities/pull/4

2021-12-10 17:06 UTC, closed without merging